### ISSUE TITLE
Can i share this script?

### ISSUE THREAD

**Issue by lilcsz** [Eskander/myanimelist-bbcode-toolbar#15]
I converted this script to browser extension. can i share with credits?

**Comment by Eskander** [comment]
Yeah sure, I was planning on creating an extension at some point anyway.

**Comment by lilcsz** [comment]
GM is not working on extension and I have JS error on last line: Uncaught SyntaxError Unexpected end of input

**Comment by Eskander** [comment]
Well it is expected to not work directly without modifications. The GM_ API is only for userscripts, you'll have to port the script to work with WebExtension API.
